include: package:lints/recommended.yaml
analyzer:
  exclude:  [ lib/app/setup.**.dart]

  errors:
    missing_required_param: error
    prefer_const_declarations: error
    prefer_const_constructors: error
    sort_constructors_first: warning
    avoid_unused_constructor_parameters: warning
    avoid_print: warning


linter:
  rules:
    missing_required_param: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    sort_constructors_first: true
    avoid_unused_constructor_parameters: true
    avoid_print: true
